# Generated by Django 5.1.1 on 2024-09-10 12:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_ourservice_options_alter_ourservice_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=255, verbose_name='Title of the Block')),
                ('title', models.CharField(max_length=255, verbose_name='Title of the Block')),
                ('content', models.TextField(verbose_name='Content Description')),
                ('images', wagtail.fields.StreamField([('templated', 1)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('image_1', 0), ('image_2', 0)]], {})})),
            ],
            options={
                'verbose_name': 'Why project',
                'verbose_name_plural': 'Why projects',
            },
        ),
    ]
