# Generated by Django 5.1.1 on 2024-09-10 17:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_ourteam'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='our_team',
            field=wagtail.fields.StreamField([('templated', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'max_num': 1, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.EmailBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'min_length': 10, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('picture', 1), ('first_name', 2), ('second_name', 2), ('email', 3), ('phone', 4), ('linkedIn', 5), ('role', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 5}), 9: ('wagtail.blocks.StructBlock', [[('block_title', 0), ('title', 0), ('members', 8)]], {})}),
        ),
        migrations.CreateModel(
            name='BecomeVolunteerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textshow', models.TextField(null=True, verbose_name="the message to display on the 'Become a volunteer section'")),
                ('background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='this image will be in the background section of the page.')),
                ('call_to_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='The link to the page where the volunteers registration form will be!')),
            ],
        ),
    ]
