# Generated by Django 5.1.1 on 2024-09-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_ourteam_our_team_becomevolunteersection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomevolunteersection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='becomevolunteersection',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='becomevolunteersection',
            name='textshow',
        ),
    ]
