# Generated by Django 5.1.1 on 2024-09-10 18:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_becomevolunteersection_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomevolunteersection',
            name='theblock',
            field=wagtail.fields.StreamField([('templated', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_num': 1, 'required': True, 'verbose_name': "the message to display on the 'Become a volunteer section'"}), 1: ('wagtail.blocks.PageChooserBlock', (), {'max_num': 1, 'required': True, 'verbose_name': 'The page where the volunteers registration form will be!'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True, 'verbose_name': 'this image will be in the background section of the page.'}), 3: ('wagtail.blocks.StructBlock', [[('textshow', 0), ('action_page', 1), ('background_image', 2)]], {})}, null=True),
        ),
    ]
