# Generated by Django 5.1.1 on 2024-09-10 19:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_becomevolunteersection_theblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationsFundsAndScholars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', wagtail.fields.StreamField([('tamplated', 4)], block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of received donations', 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'The amount raised, in US dollars!', 'required': True}), 2: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of scholars in the project', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This the image that will be the background of the section.', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('donations', 0), ('funds', 1), ('scholars', 2), ('background_image', 3)]], {})})),
            ],
        ),
    ]
