# Generated by Django 5.1.1 on 2024-09-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_donationsfundsandscholars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsfundsandscholars',
            options={'verbose_name': 'Donations Funds and Scholars', 'verbose_name_plural': 'Donations Funds and Scholars'},
        ),
    ]
