# Generated by Django 5.1.1 on 2024-09-24 14:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_volunteerjoinpage'),
        ('snippets', '0011_alter_donationsfundsandscholars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomevolunteersection',
            name='theblock',
            field=wagtail.fields.StreamField([('templated', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_num': 1, 'required': True, 'verbose_name': "the message to display on the 'Become a volunteer section'"}), 1: ('wagtail.blocks.PageChooserBlock', (), {'max_num': 1, 'page_type': ['base.VolunteerJoinPage'], 'required': True, 'verbose_name': 'The page where the volunteer registration form will be'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True, 'verbose_name': 'this image will be in the background section of the page.'}), 3: ('wagtail.blocks.StructBlock', [[('textshow', 0), ('action_page', 1), ('background_image', 2)]], {})}, null=True),
        ),
        migrations.CreateModel(
            name='DonateButtonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(help_text='Text for the donate button', max_length=100)),
                ('donate_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.donatepage', verbose_name='Choose the donate page')),
            ],
        ),
    ]
