# Generated by Django 5.1.1 on 2024-09-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_alter_becomevolunteersection_theblock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonateButtonLink',
        ),
    ]
