# Generated by Django 5.1.1 on 2024-09-05 14:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_block',
            field=wagtail.fields.StreamField([('templated', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Write the main display text', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display on the button', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'The page the button links to', 'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('transparent', 'Transparent')], 'help_text': 'Choose the color of the button'}), 4: ('wagtail.blocks.StructBlock', [[('button_text', 1), ('button_link', 2), ('button_color', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Add more call-to-action buttons', 'max_num': 5, 'min_num': 1, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('hero_text', 0), ('cta_buttons', 5)]], {})}, help_text='Block for Hello Section', null=True),
        ),
    ]
