# Generated by Django 5.1.1 on 2024-09-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_hero_block'),
        ('snippets', '0002_alter_ourservice_options_alter_ourservice_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.ourservice'),
        ),
    ]
