# Generated by Django 5.1.1 on 2024-09-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_whyproject'),
        ('snippets', '0006_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ourteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.ourteam'),
        ),
    ]
