# Generated by Django 5.1.1 on 2024-09-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_callforvolunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='callforvolunteer',
            new_name='call_for_volunteer',
        ),
    ]
