# Generated by Django 5.1.1 on 2024-09-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_donations_sunds_and_scholars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='donations_sunds_and_scholars',
            new_name='donations_funds_and_scholars',
        ),
    ]
