# Generated by Django 5.1.1 on 2024-09-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250, verbose_name='Display Name')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='Short Name')),
                ('org_name', models.CharField(max_length=250, verbose_name='Organization Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='General Email Address')),
                ('telephone', models.CharField(blank=True, max_length=13, verbose_name='General Telephone line')),
                ('Facebook', models.URLField(blank=True, verbose_name='Facebook Page')),
                ('Instagram', models.URLField(blank=True, verbose_name='Instragram')),
                ('LinkedIn', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('Twitter', models.URLField(blank=True, verbose_name='X (formaly Twitter)')),
                ('icon_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Icon Logo')),
                ('rectangle_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Rectangle Logo')),
                ('square_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Square Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
