# Generated by Django 5.1.1 on 2024-09-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contactformsubmission_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Loaction of the organization'),
        ),
    ]
