# Generated by Django 5.1.1 on 2024-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sitesettings_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='address',
            new_name='location_address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Street address of the organization'),
        ),
    ]
