# Generated by Django 5.1.1 on 2024-09-23 20:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_contactmessage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_block', wagtail.fields.StreamField([('templated', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This title will display on the page welcome section!', 'max_num': 1, 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('welcome_text', 0)]], {})}, help_text='Block for Hello Section', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
