# Generated by Django 5.1.1 on 2024-09-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_donatepage'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='hero_block',
        ),
        migrations.AddField(
            model_name='donatepage',
            name='donate_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='donate_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='donate_page_title',
            field=models.CharField(help_text='this page is a transimission to the actual fund collecting page. So use titles and messages tha acknowledge the donor!', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='patternship_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Rectangle Logo'),
        ),
    ]
