# Generated by Django 5.1.1 on 2024-09-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_donatepage_patternship_image'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='contact_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.contactus', verbose_name='Contact Us Page'),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='donate_page_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='patternship_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image of patternship'),
        ),
    ]
