# Generated by Django 5.1.1 on 2024-09-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_donatepage_contact_us_page_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerJoinPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('volunteer_section_title', models.CharField(help_text='Secondary title for the volunteer page', max_length=255, null=True)),
                ('volunteership_message', models.TextField(help_text='A short message to attract volunteers', null=True)),
                ('form_link', models.URLField(help_text='External URL link to the form (e.g. Google Form)', null=True)),
                ('button_text', models.CharField(help_text='Text displayed on the form link button', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
