# Generated by Django 5.1.1 on 2024-09-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_volunteerjoinpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donate_button_text',
            field=models.CharField(blank=True, help_text='Text for the donate button', max_length=100, null=True, verbose_name='Donate Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donate_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.donatepage', verbose_name='Choose the donate page'),
        ),
    ]
